# Generated by Django 2.1 on 2018-08-19 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStats',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('categories', models.SmallIntegerField()),
                ('books', models.SmallIntegerField()),
                ('authors', models.SmallIntegerField()),
                ('links', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'book_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Unknown Author', max_length=128, unique=True, verbose_name='Name')),
                ('url', models.URLField(db_index=True, default='', max_length=255, unique=True, verbose_name='Original-URL')),
                ('uuid', models.UUIDField(default=uuid.UUID('fb80805e-a3d5-11e8-822c-e0946797bb2a'), verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Year')),
                ('isbn', models.CharField(db_index=True, max_length=13, verbose_name='ISBN')),
                ('pages', models.PositiveSmallIntegerField(verbose_name='Pages')),
                ('summary', models.TextField(blank=True, db_index=True, default='', null=True, verbose_name='Summary')),
                ('description', models.TextField(blank=True, db_index=True, default='', null=True, verbose_name='Description')),
                ('uuid', models.UUIDField(default='', unique=True, verbose_name='UUID')),
                ('url', models.URLField(db_index=True, default='', max_length=255, unique=True, verbose_name='Original-URL')),
                ('image', models.URLField(default='', max_length=255, verbose_name='Image-URL')),
                ('language', models.CharField(default='en', max_length=2, verbose_name='Language-Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('authors', models.ManyToManyField(to='catalog.Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-updated_at'],
                'get_latest_by': '-updated_at',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='None', max_length=128, verbose_name='Name')),
                ('url', models.URLField(db_index=True, default='', max_length=255, unique=True, verbose_name='Original-URL')),
                ('uuid', models.UUIDField(default=uuid.UUID('fb8311f2-a3d5-11e8-822c-e0946797bb2a'), verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FeedUuid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Feed-ID')),
                ('uuid', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Feed-UUID',
                'verbose_name_plural': 'Feed-UUIDs',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=255, unique=True, verbose_name='Download-URL')),
                ('format', models.CharField(db_index=True, max_length=4, verbose_name='Format')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Book')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
        migrations.RunSQL(
            """
            CREATE VIEW IF NOT EXISTS book_stats AS
                select count(*) as id,* from
                    (select count(*) as books from catalog_book),
                    (select count(*) as authors from catalog_author),
                    (select count(*) as links from catalog_link),
                    (select count(*) as categories from catalog_category)
            """
        ),
    ]

