"""
Django settings for base project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('OPDSPROXY_SECRET_KEY', 'k@a#ywzjd8+ig7)=ax+0qj##29u301wr1=pe2*4@uk^qsyvlxr')

# SECURITY WARNING: don't run with debug turned on in production!
DJANGO_ENV = os.environ.get('OPDSPROXY_DJANGO_ENV', 'development')
DEBUG = bool(os.environ.get('OPDSPROXY_DEBUG', True))
if DJANGO_ENV is 'production':
    DEBUG = False

ALLOWED_HOSTS = os.environ.get('OPDSPROXY_ALLOWED_HOSTS', '*').split(',')

# Application definition
INSTALLED_APPS = [
    #'channels',
    'ws.apps.WsConfig',
    'catalog.apps.CatalogConfig',
    'corsheaders',
    'markdownify',
    'pipeline',
    'rest_framework',
    'rest_framework_jwt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'pipeline.middleware.MinifyHTMLMiddleware',
]

ROOT_URLCONF = 'base.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'base.wsgi.application'
#ASGI_APPLICATION = 'base.routing.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('OPDSPROXY_DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('OPDSPROXY_DB_NAME', os.path.join(BASE_DIR, 'data', 'opds.db')),
        'USER': os.environ.get('OPDSPROXY_DB_USER', ''),
        'PASSWORD': os.environ.get('OPDSPROXY_DB_PASS', ''),
        'HOST': os.environ.get('OPDSPROXY_DB_HOST', ''),
        'PORT': os.environ.get('OPDSPROXY_DB_PORT', ''),
    }
}

# django-cors-middleware settings
# https://github.com/zestedesavoir/django-cors-middleware
CORS_ORIGIN_WHITELIST = (
    'localhost:8080',
)
CORS_ALLOW_METHODS = (
    'GET',
    'POST',
)

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = os.environ.get('OPDSPROXY_LANGUAGE_CODE', 'en')
LANGUAGES = {
    ('de', 'German'),
    ('en', 'English'),
}

TIME_ZONE = os.environ.get('OPDSPROXY_TIME_ZONE', 'UTC')
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'pipeline.storage.PipelineStorage'
STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, 'base', 'static'),
    os.path.join(BASE_DIR, 'static'),
]
#STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
    # 'django.contrib.staticfiles.finders.DefaultStorageFinder',
]

PIPELINE = {
    'PIPELINE_ENABLED': True,
    'PIPELINE_COLLECTOR_ENABLED': True,
    'STYLESHEETS': {
        'app': {
            'source_filenames': (
                'base/bootstrap/dist/css/bootstrap.min.css',
                'base/fontawesome/web-fonts-with-css/css/fontawesome-all.min.css',
            ),
            'output_filename': 'css/app.css',
            'extra_context': {},
        },
    },
    'JAVASCRIPT': {
        'app': {
            'source_filenames': (
                'base/jquery/dist/jquery.slim.min.js',
                'base/popper.js/dist/umd/popper.min.js',
                'base/bootstrap/dist/js/bootstrap.min.js',
                'base/opds-proxy.js',
            ),
            'output_filename': 'js/app.js',
        }
    },
    'COMPILERS': (
        'pipeline.compilers.sass.SASSCompiler',
    )
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

JWT_AUTH = {
    'JWT_ALLOW_REFRESH': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=1),
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
}